databases:
  - name: dropearn-db
    databaseName: dropearn
    user: dropearn_user
    plan: free
    region: oregon

services:
  - type: web
    name: dropearn-api
    runtime: node
    region: oregon
    plan: free

    buildCommand: npm run build

    startCommand: npm start

    healthCheckPath: /api/healthz

    envVars:
      - key: PORT
        value: 10000

      - key: NODE_ENV
        value: production

      - key: DATABASE_URL
        fromDatabase:
          name: dropearn-db
          property: connectionString
